<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713165807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add email_message: the metadata-only Gmail mirror for inbox triage.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE email_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, gmail_message_id VARCHAR(64) NOT NULL, gmail_thread_id VARCHAR(64) NOT NULL, subject TEXT NOT NULL, snippet TEXT DEFAULT NULL, from_name TEXT DEFAULT NULL, from_email VARCHAR(320) NOT NULL, received_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, category VARCHAR(32) NOT NULL, category_reason JSON DEFAULT NULL, score INT NOT NULL, is_unread BOOLEAN NOT NULL, is_starred BOOLEAN NOT NULL, label_ids JSON DEFAULT NULL, has_list_unsubscribe BOOLEAN NOT NULL, unsubscribe_url TEXT DEFAULT NULL, dismissed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_owner_id INT NOT NULL, connected_account_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B7D58B09EB185F9 ON email_message (user_owner_id)');
        $this->addSql('CREATE INDEX IDX_B7D58B023FB3CA8 ON email_message (connected_account_id)');
        $this->addSql('CREATE INDEX idx_email_message_user_received ON email_message (user_owner_id, received_at)');
        $this->addSql('CREATE INDEX idx_email_message_user_category_received ON email_message (user_owner_id, category, received_at)');
        $this->addSql('CREATE INDEX idx_email_message_user_sender ON email_message (user_owner_id, from_email)');
        $this->addSql('CREATE UNIQUE INDEX uniq_email_message_account_gmail_id ON email_message (connected_account_id, gmail_message_id)');
        $this->addSql('ALTER TABLE email_message ADD CONSTRAINT FK_B7D58B09EB185F9 FOREIGN KEY (user_owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE email_message ADD CONSTRAINT FK_B7D58B023FB3CA8 FOREIGN KEY (connected_account_id) REFERENCES connected_account (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE email_message DROP CONSTRAINT FK_B7D58B09EB185F9');
        $this->addSql('ALTER TABLE email_message DROP CONSTRAINT FK_B7D58B023FB3CA8');
        $this->addSql('DROP TABLE email_message');
    }
}
