<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260713142617 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add connected_account for third-party integrations, external sync columns on calendar_event, and the Messenger queue table.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE connected_account (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, provider VARCHAR(64) NOT NULL, external_account_id VARCHAR(255) DEFAULT NULL, display_name VARCHAR(255) DEFAULT NULL, credentials TEXT NOT NULL, scopes JSON DEFAULT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(32) NOT NULL, last_error TEXT DEFAULT NULL, sync_state JSON DEFAULT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EEC6115D9EB185F9 ON connected_account (user_owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_connected_account_user_provider_external ON connected_account (user_owner_id, provider, external_account_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE connected_account ADD CONSTRAINT FK_EEC6115D9EB185F9 FOREIGN KEY (user_owner_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE calendar_event ADD external_uid VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE calendar_event ADD external_href VARCHAR(512) DEFAULT NULL');
        $this->addSql('ALTER TABLE calendar_event ADD external_etag VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE calendar_event ADD last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE calendar_event ADD connected_account_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE calendar_event ADD CONSTRAINT FK_57FA09C923FB3CA8 FOREIGN KEY (connected_account_id) REFERENCES connected_account (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_57FA09C923FB3CA8 ON calendar_event (connected_account_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_calendar_event_account_external_uid ON calendar_event (connected_account_id, external_uid)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE connected_account DROP CONSTRAINT FK_EEC6115D9EB185F9');
        $this->addSql('DROP TABLE connected_account');
        $this->addSql('DROP TABLE messenger_messages');
        $this->addSql('ALTER TABLE calendar_event DROP CONSTRAINT FK_57FA09C923FB3CA8');
        $this->addSql('DROP INDEX IDX_57FA09C923FB3CA8');
        $this->addSql('DROP INDEX uniq_calendar_event_account_external_uid');
        $this->addSql('ALTER TABLE calendar_event DROP external_uid');
        $this->addSql('ALTER TABLE calendar_event DROP external_href');
        $this->addSql('ALTER TABLE calendar_event DROP external_etag');
        $this->addSql('ALTER TABLE calendar_event DROP last_synced_at');
        $this->addSql('ALTER TABLE calendar_event DROP connected_account_id');
    }
}
