<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260713175140 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add sender_rule, and email_message.auto_category to remember the classifier verdict a user rule overrides.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sender_rule (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, sender_email VARCHAR(320) NOT NULL, verdict VARCHAR(32) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_owner_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B9325A1F9EB185F9 ON sender_rule (user_owner_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_sender_rule_user_sender ON sender_rule (user_owner_id, sender_email)');
        $this->addSql('ALTER TABLE sender_rule ADD CONSTRAINT FK_B9325A1F9EB185F9 FOREIGN KEY (user_owner_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // Three steps, not one. Postgres refuses to add a NOT NULL column with no
        // default to a table that already has rows, and email_message does — the
        // generator's single-statement version fails on any real database.
        //
        // Existing rows predate sender rules, so whatever the classifier decided is
        // still the effective category: copy it across.
        $this->addSql('ALTER TABLE email_message ADD auto_category VARCHAR(32) DEFAULT NULL');
        $this->addSql('UPDATE email_message SET auto_category = category');
        $this->addSql('ALTER TABLE email_message ALTER COLUMN auto_category SET NOT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE sender_rule DROP CONSTRAINT FK_B9325A1F9EB185F9');
        $this->addSql('DROP TABLE sender_rule');
        $this->addSql('ALTER TABLE email_message DROP auto_category');
    }
}
